#!/bin/bash

cd

if [ $(id -u) -eq 0 ]
then
        clear
else
        if echo $(id) |grep sudo > /dev/null
        then
        clear
        echo "Voce não é root"
        echo "Seu usuario esta no grupo sudo"
        echo -e "Para virar root e fazer a instalação execute \033[1;31msudo su\033[0m"
        exit
        else
        clear
        echo -e "Vc pecisa esta como root para poder fazer a instalção, Para virar root execute \033[1;31msu\033[0m e digite sua senha root"
        exit
        fi
fi


if yum -y update
then
yum -y update
yum -y install git
git clone https://github.com/redeviver/r3v1v3r/VpsPack.git
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
clear
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mvpspack \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
clear
cd VpsPack
rm -rf README.md
rm -rf install
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
echo -e "\033[1;33mConcluido, Execute o comando \033[1;32mVpsPack\033[1;33m como root \033[0m"
else
apt-get update
apt-get install -y git
git clone https://github.com/redeviver/r3v1v3r/VpsPack.git
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/VpsPackdir 2>/dev/null
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/criarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/criarusuario > /bin/criarusuario
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/deletarusuario > /bin/deletarusuario
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/vpspack 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/vpspack > /bin/vpspack
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/redeviver/r3v1v3r/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
clear
echo -e "\033[1;32mInstalacao concluida\n\033[1;30mExecute:"
echo -e "\n\033[1;32mvpspack \033[1;30mMenu com opcoes"
echo -e "\033[1;32mcriarusuario \033[1;30mCriar usuario com data e limite"
echo -e "\033[1;32mdeletarusuario \033[1;30mDeletar usuario ou apenas desconectar"
echo -e "\033[1;32mredefinirusuario \033[1;30mAlterar data, senha, etc, de um usuario"
echo -e "\033[1;32mlimite \033[1;30mLimite de logins simultaneos\033[0m"
clear
cd VpsPack
rm -rf README.md
rm -rf install
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done
echo -e "\033[1;37mConcluido, Execute o comando \033[1;33mVpsPack\033[1;37m como root \033[0m"
fi
cd
rm -rf install 2> /dev/null
rm -rf VpsPack 2> /dev/null
